backend:
  name: git-gateway
  branch: master
local_backend: true

# Global media folder (fallback)
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: "img" # Relative to the entry folder
    public_folder: "./img" # Relative path in the markdown source
    extension: "mdx"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Hero Image", name: "image", widget: "image"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
